### ISSUE TITLE
Header/Nav

### ISSUE THREAD

**Issue by sumeetgrewal** [CodetheChangeFoundation/ywca#2]
**Initial implementation of NavBar** 
- Fixed to top of screen
- Make use of logo and font (Gotham) 
- Test by creating nav items from Admin Panel
- Black underline under current page
- Hover style (underline in different color?)

**Comment by klapeyre** [comment]
Pulled new master and created a new branch for nav and header. Still needs a little bit of work, but mostly done. @ArielleMurad is going to start on custom-title field
